# Header
menu:
  Home: /
  Archivos: /archives
  Sobre Mi: /Sobre-Mi
rss: /atom.xml

# adding RSS feed

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links.ejs
# - twitterfeed

# Sitemap
sitemap:
    path: sitemap.xml

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Other Services
google-site-verification: -O9TBic0q6AxstDKl1Jeg-FyNMsekiBTiONCKiRK1eg
google_analytics:
favicon: \favicon.png

# Open graph
twitter: hamburgcaseras
google_plus: 113312808511491158489
pinterest: hamburguesascaseras
pinterest-rich-pin: 'true'
facebook: Hamburguesascaseras-854565941348167/
fb_admins: tonybonano
fb_app_id: Hamburguesascaseras-854565941348167
